ALTER TABLE assets
    ADD COLUMN IF NOT EXISTS is_private      BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS public_read     BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS public_download BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS public_write    BOOLEAN NOT NULL DEFAULT FALSE;
